[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hypersync"
version = "0.1"
description = "HyperSync is Python for the simulation, analysis, and visualization of the synchronisations of oscillators with group (higher-order) interactions."
authors = [
  { name = "Maxime Lucas", email = "maxime.lucas.work@gmail.com" },
]
requires-python = ">=3.8"
license = {file = "LICENSE.md"}
readme = "README.md"
